name: Node Continous Integration
on: push
jobs:
  build-node:
    name: Build Node
    runs-on: ubuntu-latest
    container: node:14
    steps: 
        - run: node --version
        - run: npm --version
        - run: actions/checkout@v2
        - run: dir